### ISSUE TITLE
[9.0] Pos_access_right: black screen when opening POS

### ISSUE THREAD

**Issue by vdewulf** [OCA/pos#223]
With version 9.0 on commit e520aab, when starting a new POS session with module pos_access_right installed, the POS screen is totally black, showing a javascript error:

```
http://localhost:8069/web/content/562-96c337a/point_of_sale.assets.js:370
Traceback:
gui.Gui.prototype.display_access_right@http://localhost:8069/web/content/562-96c337a/point_of_sale.assets.js:370:1
start@http://localhost:8069/web/content/562-96c337a/point_of_sale.assets.js:377:94
OdooClass.extend/Class.include/</prototype[name]</<@http://localhost:8069/web/content/422-89e8e19/web.assets_common.js:2537:368

```
# Steps to reproduce the issue
- install Odoo version 9.0
- run Odoo on an empty DB 
- install POS module
- run a POS session: everything OK
- install pos_access_right module
- run a POS session: screen is black

**Comment by vdewulf** [comment]
@legalsylvain Have you seen the same problem recently? Thanks!

**Comment by legalsylvain** [comment]
Hi @vdewulf. No I did'nt face the problem. 2 things to investivage : 
- Did you reproduce the bug in OCA Instance runbot ? (i just rebooted it, because it was broken, you'll can test in a while)
- Could you update your log with debug mode activated ? The present log are useless to understand the problem.

regards

**Comment by vdewulf** [comment]
Hello @legalsylvain. 

- I just tried on the runbot and I got the same result (black screen).

- I tested on my local odoo with debug mode activated but I'm not certain that it's what you needed. What do I need to do to get the log level needed? Here is the error:
```
http://localhost:8069/pos_access_right/static/src/js/pos_access_right.js:24
Retraçage :
gui.Gui.prototype.display_access_right@http://localhost:8069/pos_access_right/static/src/js/pos_access_right.js:24:1
start@http://localhost:8069/pos_access_right/static/src/js/pos_access_right.js:103:13
OdooClass.extend/Class.include/</prototype[name]</<@http://localhost:8069/web/static/src/js/framework/class.js:122:35
```
Thanks a lot!

**Comment by legalsylvain** [comment]
Hi @vdewulf. I reduced your comment. Only the first lines are interesting. So you can see (in debug mode nly) that the bug is in the line 24 of the module pos_access_right.js

https://github.com/OCA/pos/blob/9.0/pos_access_right/static/src/js/pos_access_right.js#L24

i have no clue why there is a bug, but if you make a PR to fix it, I'll review it .

If you do so, you could investigate in this recent commit in the core (september) : 
https://github.com/odoo/odoo/commit/e14ab697727d87773dbefba11453b9edca79fc68#diff-7079065c4c089eed7b36b138df35efdf

and maybe try to add a test like 'if user !== undefined 
here : 
https://github.com/OCA/pos/blob/9.0/pos_access_right/static/src/js/pos_access_right.js#L60

kind regards.

**Comment by houssine78** [comment]
Hi @legalsylvain it seems that is not the user that is undefined but the user.groups_id

I've no idea why groups_id is no more provisionned but it leads to a big problem for pos extension as setting an if statement to avoid the black screen just make the functionnality not enabled.

any hint is welcome!

**Comment by legalsylvain** [comment]
Well adding a if statement doesn't seems to be the good choice. 
solution 1 : make a PR to fix the problem
solution 2 : in the meantime, uninstall the buggy module. (well in fact, the bug appeared due to recent change in point of sale module).

**Comment by houssine78** [comment]
Hi @legalsylvain it seems that this would fix the problem https://github.com/AwesomeFoodCoops/odoo-production/commit/fc1ca54233476d4b789d0c661da557804596db93

this fix concerns another module from you which is very similar by design and had the same black screen problem.

**Comment by legalsylvain** [comment]
Hi. Thanks. well the problem is that it is a patch of the core. Did you tried to make a PR againt Odoo ? regards.

**Comment by houssine78** [comment]
Nope the patch is for the concerned modules. I've applied it on our repo and it fixed the problem pretty well.

**Comment by houssine78** [comment]
I lack time to follow the PR process. I just put the info here in case of someone was search for a fix.
