### ISSUE TITLE
[BUG] [11.0] [pos_order_mgmt] Incompatibility with pos_restaurant

### ISSUE THREAD

**Issue by carlos-domatix** [OCA/pos#333]
Hello,

- Go to OCA runbot / pos.
- Install pos_restaurant.
- Open session on pos.
- Click on cart button to return or view orders.
- You will get this javascript error:
![Screen Shot on Mar 13th at 11_15 AM](https://user-images.githubusercontent.com/28001484/54271192-5921dd00-4581-11e9-8663-6e727f4840b4.png)

Other bugs detected:
- Open session on pos.
- Select any table.
- Click on cart button to return or view orders.
- Click on back button.
- When you click on the previously selected table, it does not open.

**Comment by chienandalu** [comment]
Hi, @carlosDomatix Thanks for you report.

Indeed we didn't count with the restaurant screens and that behaviour and it needs to be fixed.

- For the first case, the cart icon should be hidden in the table selection screen.
- The second one seems a little bit more complex, since there's some wrong interaction the table widget.

Feel free to PR with a fix :smile:

**Comment by PierrickBrun** [comment]
Hi @chienandalu,
I've fixed the first problem in this PR https://github.com/OCA/pos/pull/337 . Fortunately, I did not have to hide the button on the floors screen.
The second problem is, as you said, more complex and I still don't know how to fix it
