### ISSUE TITLE
[11.0] [pos_order_mgmt] Customer pricelist does not apply on ticket return

### ISSUE THREAD

**Issue by Joaco1980** [OCA/pos#346]
When you make a return through the module, it includes all the negative lines, but does not include the customer's predefined prices (Professional Prices).

When returning an entire ticket to a client for an error in the discounts, and in the same ticket to include the positive lines with the correct discounts, in the negative lines the customer's rate was applied but in the lines that we added positive, the prices published by default of the POS (Public Prices)

**Comment by chienandalu** [comment]
Hi, @Joaco1980 
Is this for pos_order_return or for pos_order_mgmt?

**Comment by Joaco1980** [comment]
I have installed the two modules. It happens when you hit the return button of a ticket.

**Comment by chienandalu** [comment]
Thanks, @Joaco1980 

I checked and indeed the problem exists with the steps you gave. Some remarks:

- The issue is with the module `pos_order_mgmt` (I'll edit the issue's subject now). `pos_order_return`, wich is purely backend, doesn't even allow you to edit the return ticket.
- The issue itself is that **the return ticket doesn't get original one pricelist**.
- Anyway, **what you should do for the moment is not to mix up the return tickets with the positive ones**.
- Think also that a pricelist could be unavailable for a pos.config in the moment of making a ticket return, so we could be falling back to a wrong pricelist as well.

**Comment by Joaco1980** [comment]
If I think the solution is to make the return first and then make the new sale and so not mix it.

**Comment by chienandalu** [comment]
Sure, that's what I said :)
