### ISSUE TITLE
[RFC][12.0][pos_order_mgmt] Full return order support

### ISSUE THREAD

**Issue by dalonsod** [OCA/pos#446]
Hi,

I'd interested to implement this pending task in `pos_order_mgmt` addon:

_It's possible to return the same order over and over. To avoid so, we should load and control if there's a returned line id associated with the original order. That would be a great improvement for future revisions. This feature is implemented in the module `pos_order_return` in the back office part, but not in front office part (implemented in this this module)._

Could anyone bring me some guidelines in order to achieve this interesting but probably complex task? Anyway, I have some doubts/questions:

- The `pos_return` addon adds some fields (`returned_line_id, refund_line_ids`) to `pos.order.line` model, which are still missing in `pos_order_mgmt`. I think they should be exactly cloned to prevent compatiblity with `pos_return`. Is that correct?
- When creating the refund ticket those fields will be filled. In current `pos_return` implementation, when an incorrect quantity is filled, the `_check_return_qty()` method prevents it. Should I exactly repeat this behavior?

Are there more things to take in account?

Thanks in advance!!!

cc @legalsylvain @chienandalu

**Comment by legalsylvain** [comment]
Hi. thanks for your question. Not a very clear Point of view but : 
- ``pos_order_return`` has been created before ``pos_order_mgmt`` and are for the time being independant.
- Since ``pos_order_mgmt`` exists, some basic "return feature" is implemented in this module.
- Finally ``pos_order_return`` is now, more a module to have a traceability of the returned products.

so my proposal is : 
- Rename ``pos_order_return`` into ``pos_order_return_traceability`` and make this module depends on ``pos_order_mgmt``
- in the ``pos_order_return_traceability`` load returned_line_id, refund_line_ids, etc.... in the front office part and rewrite checks in javascript present for the time being in the function ``_check_return_qty()``. (or maybe make a call to the server, I don't know...)
- maybe remove the back office code. (It will be useless if front office code is implemented in fact). 

What is your target ? V12 ? V13 ? 
thanks.

**Comment by dalonsod** [comment]
> What is your target ? V12 ? V13 ?

v12

**Comment by dalonsod** [comment]
Hello again,

@legalsylvain I'm already depeloping part of the structure changes you proposed, focusing on `pos_order_mgmt` changes, the` pos_order_return_traceability` changes should be done later, since this two addons are still independent (and I still don't know how a module renaming OCA procedure is).

But, prior to open PR, when you say

> in the _pos_order_return_traceability_ load returned_line_id, refund_line_ids, etc.... in the front office part and rewrite checks in javascript present for the time being in the function _check_return_qty(). (or maybe make a call to the server, I don't know...)

, it that correct, or maybe you actually want to refer to `pos_order_mgmt`? I understand we want to move return fields and (an adapted) business logic from `pos_order_return` to `pos_order_mgmt`, don't we?

Thanks in advance!!!

**Comment by legalsylvain** [comment]
If you dont want to rename you can create a module pos_order_return_tracability that depends on pos_order_return (for the models) and pos_order_mgmt for the return feature that is still implemented in the front office.

I dont refer to pos_order_mgmt as I dont think that it's a good idea to add a lot of extra fields in database in pos order / pos order line model for a feature that is interesting in a very specific case of tracability.

Am I more clear ? If not please mention your WIP branch and I'll comment on it directly.

Thanks.

**Comment by dalonsod** [comment]
Thanks for the explanations @legalsylvain 

I'll try to move the code to the new module `pos_order_return_traceability` as you comment. If I finally need any hook method of `pos_order_mgmt` I'll do a PR for that.

**Comment by legalsylvain** [comment]
You can make a single PR with : 
- the new module ``pos_order_return_traceability``
- some changes in ``pos_order_mgmt`` and ``pos_order_return``, your hook for exemple (if it doesn't break nothing, of course;-))

it will be more easy to review (and to develop, for you).

kind regards.

**Comment by dalonsod** [comment]
That'd be great thanks!

**Comment by dalonsod** [comment]
Closing, continued on #451
