### ISSUE TITLE
Printing of delivery notes in Tpv of odoo 12

### ISSUE THREAD

**Issue by Joandelfi** [OCA/pos#704]
Hello, would someone know how to configure odoo to print delivery notes on the POS with the pos_stock_picking_invoice module, or with this other pos_save_quotations

**Comment by etobella** [comment]
Try to speak in english please, as the main language for oca is english. You can use spanish on the specific localization

**Comment by legalsylvain** [comment]
Hi. @Joandelfi. Where are the modules you are mentioning ?

**Comment by Joandelfi** [comment]
https://github.com/OCA/pos/tree/12.0/pos_stock_picking_invoice_link#usage
https://apps.odoo.com/apps/modules/12.0/pos_save_quotations/

**Comment by Joandelfi** [comment]
https://apps.odoo.com/apps/modules/12.0/pos_save_quotations/
https://github.com/OCA/pos/tree/12.0/pos_stock_picking_invoice_link#usage

**Comment by chienandalu** [comment]
@Joandelfi 

- The first module is just for internally relate pos pickings with their invoices. You'll see them in the backend. You'd need an extension like [`account_invoice_report_grouped_by_picking`](https://github.com/OCA/account-invoice-reporting/tree/12.0/account_invoice_report_grouped_by_picking) but for POS instead of Sale Orders.
- The second module doesn't belong to the OCA realm.

**Comment by Joandelfi** [comment]
Ok thanks i will try
